// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5kctx-Ql3DhWMDAr0Uwd7onUshMoTJI',
    appId: '1:74806536200:web:49cd652b3f31f2d22fc9bd',
    messagingSenderId: '74806536200',
    projectId: 'ravene-e61ec',
    authDomain: 'ravene-e61ec.firebaseapp.com',
    databaseURL: 'https://ravene-e61ec-default-rtdb.firebaseio.com',
    storageBucket: 'ravene-e61ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMNB7F93sjsh8WSWa_yZ0MGVbULERBVj4',
    appId: '1:74806536200:android:7fc9ca0da0f07e312fc9bd',
    messagingSenderId: '74806536200',
    projectId: 'ravene-e61ec',
    databaseURL: 'https://ravene-e61ec-default-rtdb.firebaseio.com',
    storageBucket: 'ravene-e61ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS3jOVJQ3GM-7AsPnMXMpAob_dpoJpRZI',
    appId: '1:74806536200:ios:536f7ea054039b602fc9bd',
    messagingSenderId: '74806536200',
    projectId: 'ravene-e61ec',
    databaseURL: 'https://ravene-e61ec-default-rtdb.firebaseio.com',
    storageBucket: 'ravene-e61ec.appspot.com',
    iosBundleId: 'com.example.ravene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS3jOVJQ3GM-7AsPnMXMpAob_dpoJpRZI',
    appId: '1:74806536200:ios:536f7ea054039b602fc9bd',
    messagingSenderId: '74806536200',
    projectId: 'ravene-e61ec',
    databaseURL: 'https://ravene-e61ec-default-rtdb.firebaseio.com',
    storageBucket: 'ravene-e61ec.appspot.com',
    iosBundleId: 'com.example.ravene',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB5kctx-Ql3DhWMDAr0Uwd7onUshMoTJI',
    appId: '1:74806536200:web:d04aab01af587a392fc9bd',
    messagingSenderId: '74806536200',
    projectId: 'ravene-e61ec',
    authDomain: 'ravene-e61ec.firebaseapp.com',
    databaseURL: 'https://ravene-e61ec-default-rtdb.firebaseio.com',
    storageBucket: 'ravene-e61ec.appspot.com',
  );
}
